export default ["2",
"A Good Thing",
"A Little Bit",
"A Little Bit Longer",
"A Story",
"Aerosmith",
"All That You Can't Leave Behind",
"American films",
"Attack",
"Billboard.*",
"Bismuth-209",
"By the Way",
"Canopy",
"Cello",
"Chair",
"Ciara",
"Coming out",
"Debut albums",
"Debut singles",
"Deer",
"Doing It",
"English-language films",
"Existential quantification",
"Feces",
"Hope That We Can Be Together Soon",
"I Decided",
"If You Have to Ask",
"KILL",
"LOOK",
"Need",
"Need to know",
"New York City",
"Paste",
"Smile",
"TED",
"That that is is that that is not is not is that it it is",
"Thing",
"Universal quantification",
"WANT",
"Want",
"YOU",
".* years",
"thing",
"things",
"Debut albums",
"good thing",
"one day",
".* minutes",
".* percent"]
